service: app

provider:
  name: google
  runtime: nodejs16
  region: asia-northeast1
  project: better-gpt-ab774
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.config/gcloud/application_default_credentials.json

frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  patterns:
    - '!node_modules/**'

functions:
  api:
    handler: http
    events:
      - http: path
